---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
    name: sealed-secrets
    namespace: kube-system
    annotations:
        fluxcd.io/automated: "true"
spec:
    releaseName: sealed-secrets
    chart:
        name: stable/sealed-secrets
